#cloud-config
vendor_data: {enabled: false}

keyboard:
  layout: us
locale: en_US.UTF-8
timezone: America/Los_Angeles

prefer_fqdn_over_hostname: false
hostname: oit-cinit-sta # SET HOSTNAME HERE

# Force default partition to use all available space (default in Ubuntu is .5x available space for default LVM, don't force Growpart for LVM)
resize_rootfs: true
growpart:
  devices: [/]
  ignore_growroot_disabled: false
  mode: auto

network:
  version: 2
  ethernets:
    id0:
      match: 
        name: eth*
      addresses:
        - 10.168.45.99/24 # THIS SHOULD BE CHANGED TO MATCH SERVER
      gateway4: 10.168.45.1 # MATCH THIS TO ABOVE SUBNET
      nameservers:
        search: 
          - csustan.edu
        addresses:
          - 10.168.73.31
          - 10.168.76.32

ntp:
  enabled: true
  servers:
    - time.csustan.edu
  pools: 
    - 0.us.pool.ntp.org
    - 1.us.pool.ntp.org
    - 2.us.pool.ntp.org
    - 3.us.pool.ntp.org

disable_root: true
ssh_pwauth: false

# disable all Ubuntu Pro features
ubuntu_pro:
  features: {disable_auto_attach: true}
  enable: []
  enable_beta: []

users:
  - name: ansible
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      -

ansible:
  package_name: ansible-core
  install_method: distro
  run_user: ansible
  pull:
    - url: https://github.com/wjordan-csustan/ansible.git
      playbook_names: 
        - ubuntu.yml # eventually this will be replaced with the server-specific playbook



