#cloud-config
vendor_data: {enabled: false}

keyboard:
  layout: us
locale: en_US.UTF-8
timezone: America/Los_Angeles

prefer_fqdn_over_hostname: false
hostname: oit-cinit-sta # SET HOSTNAME HERE

# Force default partition to use all available space (default in Ubuntu is .5x available space for default LVM, don't force Growpart for LVM)
resize_rootfs: true
growpart:
  devices: [/]
  ignore_growroot_disabled: false
  mode: auto

network:
  version: 2
  ethernets:
    id0:
      match: 
        name: eth*
      addresses:
        - 10.168.45.99/24 # THIS SHOULD BE CHANGED TO MATCH SERVER
      gateway4: 10.168.45.1 # MATCH THIS TO ABOVE SUBNET
      nameservers:
        search: 
          - csustan.edu
        addresses:
          - 10.168.73.31
          - 10.168.76.32

ntp:
  enabled: true
  servers:
    - time.csustan.edu
  pools: 
    - 0.us.pool.ntp.org
    - 1.us.pool.ntp.org
    - 2.us.pool.ntp.org
    - 3.us.pool.ntp.org

disable_root: true
ssh_pwauth: false

# disable all Ubuntu Pro features
ubuntu_pro:
  features: {disable_auto_attach: true}
  enable: []
  enable_beta: []

users:
  - name: ansible
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDqhiget/MhesJ1/t2t4x9Mgv8Hd1wJAFJH5HOrmPyg+gVkhN9Yo3hwLLRXXsevXRN9J15RAl+R/BPUJVspRmUMbS4sL+t8cjfyyX7E28RC6VxwmPMoAcpbD5FdXoh27NOxCs7WzUIZcm691g4CqkuL+YnBd0mNniB6R98IXPCAn1BPxU8EvJUBgQVQoPSSCcjmhrV2AKKzUvgDh0zXbz/kvvSv/A9KHw3Uw3CcC1RJ8zJmnRgrCxhunJKiSLugrYB1LYnke3duCPrZGne/ft5wuW6msNV5RCPv92m+Ceaza8e5v5zzLw6iSKRKKdqbLm+EqbbAGsiYnT5KwZIhuI4AukM2/tgnDWOCdaN0W18gOjdMVyQ3ijhJfZcfKAXVz8RG93eXcG0oW6k5or/pRo/rtQaX5+C4XEFLBncDot8d4KySXthzO566h0pKd9RMsWSyv0HbWsP2ZSyhobEPm0QU530zZxhMGHBQOmYbZk49NN6IxSM5+C5Yts71MQTF4snc19zKy91SoGtij6zCIgwzYDZdpj2mmGIo8R6kySuO3P2B8YQF83/c3bYPBHQmu7bmn+HmqAKUpl2GdHaTM0r337XMjudDaBodz6QnuCRT77mYP+CS38d6d6o5yVUXXiVg1JpPtKaN3UjdFYexzkh0+J2/70csDOIweoY9wpa/XQ== wjordan-ssh-key-2025 PIV

ansible:
  package_name: ansible-core
  install_method: distro
  run_user: ansible
  pull:
    - url: https://github.com/wjordan-csustan/ansible.git
      playbook_names: 
        - ubuntu.yml # eventually this will be replaced with the server-specific playbook



